name: CommitLint

on: [push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Run CommitLint
        run:  npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      
      - name: Format code
        run: yarn format

      - name: Lint code
        run: yarn lint